import { useEffect, useState } from "react";
import { Check, Copy, Mail, Sparkles, X } from "lucide-react";
import { useStore } from "../../store/store";
import { draftStatusEmail } from "../../lib/claude";
import type { Project, StatusUpdate } from "../../lib/types";

export function DraftEmailPanel({ project, update, close }: { project: Project; update: StatusUpdate; close: () => void }) {
  const { all } = useStore();
  const [stage, setStage] = useState<"loading" | "ready" | "error">("loading");
  const [body, setBody] = useState("");
  const [subject, setSubject] = useState(`${project.title} — status update`);
  const [copied, setCopied] = useState(false);

  const allContacts = [...all.work.contacts, ...all.personal.contacts];
  const toEmails = (project.members ?? [])
    .map((m) => allContacts.find((c) => c.id === m.contactId))
    .filter((c): c is NonNullable<typeof c> => !!c && !!c.email)
    .map((c) => c.email);

  useEffect(() => {
    let cancelled = false;
    draftStatusEmail(project, update, all.user)
      .then((draft) => { if (!cancelled) { setBody(draft); setStage("ready"); } })
      .catch(() => { if (!cancelled) setStage("error"); });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const doCopy = async () => {
    await navigator.clipboard.writeText(body);
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
  };

  const toParam = toEmails.join(",");

  const sendViaGmail = () => {
    const url = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(toParam)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, "_blank");
  };

  const sendViaOutlook = () => {
    const url = `https://outlook.office.com/mail/deeplink/compose?to=${encodeURIComponent(toParam)}&subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url, "_blank");
  };

  return (
    <div className="overlay">
      <div className="overlay-bg" onClick={close} />
      <div className="side-panel">
        <div className="side-panel-head">
          <div style={{ width: 28, height: 28, borderRadius: 7, background: "var(--accent-soft)", color: "var(--accent)", display: "grid", placeItems: "center" }}>
            <Sparkles size={15} />
          </div>
          <div style={{ flex: 1 }}>
            <div style={{ fontSize: 14, fontWeight: 600 }}>AI Draft — Status Email</div>
            <div style={{ fontSize: 12, color: "var(--ink-3)" }}>{project.title}</div>
          </div>
          <button className="icon-btn" onClick={close}><X /></button>
        </div>

        <div className="side-panel-body">
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label className="field-label">To</label>
            <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
              {toEmails.length > 0
                ? toEmails.map((email) => <span key={email} className="chip">{email}</span>)
                : <span style={{ fontSize: 12.5, color: "var(--ink-4)", fontStyle: "italic" }}>No team member emails on file</span>
              }
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            <label className="field-label">Subject</label>
            <input className="input" value={subject} onChange={(e) => setSubject(e.target.value)} style={{ fontWeight: 500 }} />
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 6, flex: 1 }}>
            <label className="field-label" style={{ display: "flex", alignItems: "center" }}>
              Body
              {stage === "ready" && (
                <span style={{ marginLeft: "auto", color: "var(--accent-ink)", display: "flex", alignItems: "center", gap: 4, textTransform: "none", letterSpacing: 0, fontWeight: 500 }}>
                  <Sparkles size={11} /> Generated by Claude
                </span>
              )}
            </label>
            {stage === "loading" ? (
              <div style={{ border: "1px solid var(--border)", borderRadius: 7, padding: 16, display: "flex", flexDirection: "column", gap: 10 }}>
                {[100, 92, 78, 88, 60, 95, 40].map((w, i) => (
                  <div
                    key={i}
                    style={{
                      height: 9, width: `${w}%`, borderRadius: 5,
                      background: "linear-gradient(90deg,var(--surface-2),var(--border),var(--surface-2))",
                      backgroundSize: "200% 100%",
                      animation: `shimmer 1.3s ${i * 0.08}s infinite linear`,
                    }}
                  />
                ))}
                <div style={{ fontSize: 12, color: "var(--ink-3)", display: "flex", alignItems: "center", gap: 7, marginTop: 4 }}>
                  <Sparkles size={13} /> Claude is drafting from project context…
                </div>
              </div>
            ) : stage === "error" ? (
              <div style={{ border: "1px solid var(--border)", borderRadius: 7, padding: 16, fontSize: 13, color: "var(--danger)" }}>
                Couldn't reach the AI. Check your connection and retry, or add your Anthropic API key in Settings (⚙).
              </div>
            ) : (
              <textarea
                className="input"
                value={body}
                onChange={(e) => setBody(e.target.value)}
                style={{ flex: 1, minHeight: 280, fontSize: 13 }}
              />
            )}
          </div>
        </div>

        <div className="side-panel-foot">
          <button className="btn btn-primary" disabled={stage !== "ready"} onClick={sendViaGmail}>
            <Mail /> Gmail
          </button>
          <button className="btn btn-primary" disabled={stage !== "ready"} onClick={sendViaOutlook}>
            <Mail /> Outlook
          </button>
          <button className="btn btn-ghost" disabled={stage !== "ready"} onClick={doCopy}>
            {copied ? <><Check /> Copied</> : <><Copy /> Copy</>}
          </button>
          <button className="btn btn-ghost" style={{ marginLeft: "auto" }} onClick={close}>Cancel</button>
        </div>
      </div>
    </div>
  );
}
